spring.application.name=Event-Management-System

# DataBase Credentials
spring.datasource.url=jdbc:mysql://localhost:3306/event_management_system
spring.datasource.username=root
spring.datasource.password=Nikhil@mysql

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update